CREATE TABLE IF NOT EXISTS Users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  -- Change SERIAL to BIGINT UNSIGNED AUTO_INCREMENT
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    email_verified_at TIMESTAMP NULL DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  -- Change SERIAL to BIGINT UNSIGNED AUTO_INCREMENT
    role_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UserRoles (
    user_id BIGINT UNSIGNED NOT NULL,  -- Change INT to BIGINT UNSIGNED
    role_id BIGINT UNSIGNED NOT NULL,  -- Change INT to BIGINT UNSIGNED to match the Roles table's id type
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES Roles(id) ON DELETE CASCADE
);

CREATE TABLE PasswordResetTokens (
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (email, token)
);

CREATE TABLE Sessions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  -- Change SERIAL to BIGINT UNSIGNED AUTO_INCREMENT
    user_id BIGINT UNSIGNED NOT NULL,  -- Change INT to BIGINT UNSIGNED to match the Users table's id type
    ip_address BIGINT NULL DEFAULT NULL,
    user_agent TEXT NULL DEFAULT NULL,
    payload TEXT NOT NULL,
    last_activity BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- Table: RefreshTokens
CREATE TABLE RefreshTokens (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  -- Change SERIAL to BIGINT UNSIGNED AUTO_INCREMENT
    user_id BIGINT UNSIGNED NOT NULL,  -- Change INT to BIGINT UNSIGNED to match the Users table's id type
    refresh_token TEXT NOT NULL,
    ip_address VARCHAR(255) NULL DEFAULT NULL,
    user_agent TEXT NULL DEFAULT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);
