name: FASTIFY AUTHENTICATION PLUGIN CI 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix: 
        node-version: ['18.x','20.x','21.x','22.x','23.x']
    runs-on: ubuntu-latest
    services:
      mysql: 
        image: mysql:8.4.3
        env:
          MYSQL_DATABASE: 'testdb'
          MYSQL_ROOT_PASSWORD: 'testRootPassword'
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - name: RUN TEST
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: testdb
          DB_USER: root
          DB_PASSWORD: testRootPassword
        run: |
          DB_CONNECTION=mysql DB_HOST=127.0.0.1 DB_PORT=3306 DB_NAME=testdb DB_USER=root DB_PASSWORD=testRootPassword npm run db:create:tables
          npm run test